(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for int() with base 10: ''"
p3
sS'layer'
p4
S'/mnt/c/Users/Allan/Desktop/CMPS183/ProjectCheerSite/web2py/applications/start/controllers/api.py'
p5
sS'code'
p6
S'<code object <module> at 0x7fe748009330, file "/mnt/c/Users/Allan/Desktop/CMPS183/ProjectCheerSite/web2py/applications/start/controllers/api.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/mnt/c/Users/Allan/Desktop/CMPS183/ProjectCheerSite/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/mnt/c/Users/Allan/Desktop/CMPS183/ProjectCheerSite/web2py/applications/start/controllers/api.py", line 132, in <module>\n  File "/mnt/c/Users/Allan/Desktop/CMPS183/ProjectCheerSite/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/mnt/c/Users/Allan/Desktop/CMPS183/ProjectCheerSite/web2py/applications/start/controllers/api.py", line 20, in get_images\n    current_id = int(request.vars.current_id) if request.vars.current_id is not None else 0\nValueError: invalid literal for int() with base 10: \'\'\n'
p11
s.